version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    groups:
      react-query:
        patterns:
          - "@tanstack/react-query"
          - "@tanstack/react-table"
          - "@tanstack/react-virtual"
      radix:
        patterns:
          - "@radix-ui/*"
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
      include: scope
