import { StatusInvestNormalizedDataType } from "@/@types/StatusInvestNormalizedDataType";
import { StocksCalculatedDataType } from "@/@types/StocksCalculatedDataType";
import {
  getTicker,
  getPrice,
  getDY,
  getPL,
  getLPA,
  getVPA,
  calculateDPA,
  getDiscountMargin,
  calculatePayout,
  growthOrDividend,
  getROE,
  calculateCagrProfit,
  calculateDamoradanGrowth,
  calculateGrowthAverage,
  calculateBazinDiscount,
  calculateBazinFairPrice,
  calculateBazinCeelingPrice,
  calculateGrahamDiscount,
  calculateGrahamFairPrice,
  calculateGrahamCeelingPrice,
  calculateGordonDiscount,
  calculateGordonFairPrice,
  calculateGordonCeelingPrice,
  calculateD1,
  calculatePEG,
  getPSR,
} from "@/utils";

export const stocksDomain = (
  row: StatusInvestNormalizedDataType,
  risk: number,
): StocksCalculatedDataType => {
  return {
    ticker: getTicker(row),
    price: getPrice(row),
    dy: getDY(row),
    pl: getPL(row),
    lpa: getLPA(row),
    vpa: getVPA(row),
    dpa: calculateDPA(row),
    risk: risk,
    discount_margin: getDiscountMargin(),
    payout: calculatePayout(row),
    growthDividend: growthOrDividend(row),
    roe: getROE(row),
    cagrProfit: calculateCagrProfit(row),
    damodaramGrowth: calculateDamoradanGrowth(row),
    growthAverage: calculateGrowthAverage(row),
    bazinDiscount: calculateBazinDiscount(row),
    bazinFairPrice: calculateBazinFairPrice(row),
    bazinCeelingPrice: calculateBazinCeelingPrice(row),
    grahamDiscount: calculateGrahamDiscount(row),
    grahamFairPrice: calculateGrahamFairPrice(row),
    grahamCeelingPrice: calculateGrahamCeelingPrice(row),
    gordonDiscount: calculateGordonDiscount(row, risk),
    gordonFairPrice: calculateGordonFairPrice(row, risk),
    gordonCeelingPrice: calculateGordonCeelingPrice(row, risk),
    d1: calculateD1(row),
    peg: calculatePEG(row),
    psr: getPSR(row),
  };
};
